@baseUrl=https://localhost:7036
@authToken=need token here!

### GET All practices attebdabces
GET {{baseUrl}}/api/v1/practices?Page=1&Size=10
Authorization: Bearer {{authToken}}

### GET Practice by id
GET {{baseUrl}}/api/v1/practices/2f042e86-d75e-4591-a810-aca808726604
Authorization: Bearer {{authToken}}

### POST Create 
POST {{baseUrl}}/api/v1/practices
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "gokstad",
  "practiceDate": "2024-09-09T19:30:00:00.651Z"
}
### PUT Update practice
PUT {{baseUrl}}/api/v1/practices/2f042e86-d75e-4591-a810-aca808726604
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "Stavanger",
  "practiceDate": "2025-11-11T19:30:00:00.651Z"
}

### DELETE Delete Practice
DELETE {{baseUrl}}/api/v1/practices/2f042e86-d75e-4591-a810-aca808726501
Authorization: Bearer {{authToken}}