@baseUrl=https://localhost:7036

### GET ALL / BY LASTNAME

GET {{baseUrl}}/api/v1/users?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 Eksempel på JWT token, sett inn når JWT er implementert? Hvordan lage token for at disse skal fungere?

### GET BY ID

GET {{baseUrl}}/api/v1/users/8f2466af-57c3-458c-82d8-676d80573c6c
Authorization: Bearer inputTokenHere


### GET BY EMAIL

GET {{baseUrl}}/api/v1/users/email?email=sara%40abc.no
Authorization: Bearer inputTokenHere

### REGISTER USER

POST {{baseUrl}}/api/v1/users/register
Authorization: Bearer inputTokenHere

### UPDATE USER

PUT {{baseUrl}}/api/v1/users/8f2466af-57c3-458c-82d8-676d80573c6c
Authorization: Bearer inputTokenHere

### DELETE USER
DELETE {{baseUrl}}/api/v1/users/8f2466af-57c3-458c-82d8-676d80573c6c
Authorization: Bearer inputTokenHere

